### PR TITLE
various cmake improvements

### PR DESCRIPTION
**Pull request by E5ten**
bump minimum cmake version to 3.1
add LANGUAGES C to project command
use CMAKE_C_STANDARD variable instead of adding flag manually
don't set CMAKE_SOURCE_DIR (the project is not supposed to set this)
append to CMAKE_MODULE_PATH list instead of replacing it
make sure git commands are executed in CMAKE_CURRENT_SOURCE_DIR
check if VERSION_SORT is unset with "if(NOT" instead of checking if it
is empty with STREQUAL
use target_* commands instead of global add_* commands
link imported targets instead of adding library and include directory
variables
remove FindXrandr module and use Xrandr component from FindX11
use CheckCCompilerFlag module to check warning flags, instead of adding
them when gcc is in use
add warning flags and -mwindows using target_compile_options instead of
modifying CMAKE_C_FLAGS
use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR in case shot is
a subproject
use cmake -E to remove files for uninstall target instead of rm command
include GNUInstallDirs instead of assuming bin and man directories
add PRIVATE qualifier to target_* commands
add source files manually instead of using file's GLOB for proper
dependency handling
put configured headers in CMAKE_CURRENT_BINARY_DIR instead of generating
files in source tree
merge linking into one target_link_libraries call, using generator
expressions to determine what to link
use REQUIRED with find_package for X11 and Xrandr when x11 is being
targeted, and avoid erroring manually
add imported library for gdi32 and use it for linking instead of library
variable

### CODE REVIEW

**Comment by rr-** [comment]
Hey @E5ten thanks for the pull request. Are the changes ready to be merged? I updated the dependencies here. https://aur.archlinux.org/packages/shot-git/ but I guess it'll take time until they're visible

**Comment by E5ten** [comment]
I built shot on Linux as I made changes to make sure I wasn't breaking anything, but if you could verify that the windows build still works correctly that'd make me even more confident that they're good to go.

**Comment by E5ten** [comment]
Also, when you get the chance to make sure this change doesn't break building on windows, can you delete the "INTERFACE_COMPILE_OPTIONS -mwindows" line from cmake/FindGDI32.cmake, because as far as I can tell, when cmake is building an executable on windows, it automatically adds that argument.

**Comment by E5ten** [comment]
Actually, looking into it further, in addition to it appearing to me that cmake adds -mwindows on windows by default, I think it might link gdi32 by default as well, removing the need to search for it? When you test the windows build, it would help if you could remove the linking of gdi32 entirely and see if it still works.

**Comment by rr-** [comment]
@E5ten it'll take significant time until I'm able to test the Windows platform, unfortunately.

**Comment by rr-** [comment]
Alas, on Linux Mint I can't seem to be able to build this package under new cmake settings:

```
CMake Error at CMakeLists.txt:43 (add_executable):
  Target "shot" links to target "X11::X11" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


CMake Error at CMakeLists.txt:43 (add_executable):
  Target "shot" links to target "X11::Xrandr" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?


-- Generating done
-- Build files have been written to: /home/rr-/src/priv/shot/build
rr-@lightning:~/src/priv/shot/build$ apt search libx11-dev
i A libx11-dev                                                                                                                       - X11 client-side library (development headers)
rr-@lightning:~/src/priv/shot/build$ apt search libxrandr-dev
i   libxrandr-dev                                                                                                                    - X11 RandR extension library (development headers)
p   libxrandr-dev:i386                                                                                                               - X11 RandR extension library (development headers)
```

whereas this is the behavior on the old master:

```
rr-@lightning:~/src/priv/shot/build$ cmake ..
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34")
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Checking for module 'xrandr'
--   Found xrandr, version 1.5.1
-- Found XRANDR: /usr/lib/x86_64-linux-gnu/libXrandr.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rr-/src/priv/shot/build
```

**Comment by E5ten** [comment]
Ah, it seems FindX11 only includes those imported targets as of cmake 3.14, I'll switch this to use the variables when I get a chance, and see if I can find someone to test on windows or get an environment set up for it myself.

**Comment by E5ten** [comment]
I sent a large change, it definitely needs testing on windows, because it removes linking of gdi32, which from what I can tell, is automatically linked into executables on windows. It also use FindPkgConfig instead of FindX11, because FindX11 requires a much newer version of cmake to provide imported targets, and pkg_check_modules can create them itself.

**Comment by rr-** [comment]
Now it's working well on Linux Mint ✔️

**Pull request merged**
